spring:
  application:
      name: scm-wip
  aop:
    proxy-target-class: true
  sleuth:
    sampler:
      percentage: 1
  messages:
    basename: i18n/messages

# 为了传递会话，指定hystrix在调用线程上执行
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000

csb:
  mybatis:
    basePackage: com.cvte.scm.wip.infrastructure.**.mapper
    xmlLocation: classpath*:mybatis/mapper/**/*.xml
  swagger:
    basePackage: com.cvte.scm.wip
    description: WIP 接口
    version: 1.0
  redis:
    app_prefix: SCM-WIP

#设置打印日志
logging:
  level:
    tk.mybatis: DEBUG
    com.cvte.csb: DEBUG
    org.springframework.core: INFO
    org.springframework.jdbc: DEBUG
    com.cvte.scm.wip.infrastructure: DEBUG
    com.cvte.scm.demo: INFO
    com.cvte.scm.demo.**.core.mapper: DEBUG
    com.xxl: ERROR
    config: classpath:logback-spring.xml

